
import type { Metadata } from "next";
import { Exo } from "next/font/google"; 

import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import Providers from "./providers"; 
import "./globals.css";
import "swiper/css";
import { Toaster } from "sonner";
import { AppProvider } from "@/components/shared/context/CartContext";

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-exo", 
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: "FreshCart", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${exo.className} min-h-full flex flex-col`}>
        
        <Providers>
          
          <AppProvider>
            <main>
              <Navbar/>
              <Toaster richColors position="top-right" /> 
              {children}
              <Footer/>
            </main>
          </AppProvider>
          
        </Providers>
        
      </body>
    </html>
  );
}